import { useState, useCallback } from 'react';
import { Download, FileText, Copy, Check } from 'lucide-react';

interface ReportExporterProps {
  reportData: {
    id: string;
    riskScore: number;
    riskLevel: string;
    category: string;
    summary: string;
    redFlags: Array<{ title: string; explanation: string; severity: string }>;
    recommendedActions: Array<{ action: string; priority: string }>;
    psychologicalTriggers?: string[];
  };
}

export default function ReportExporter({ reportData }: ReportExporterProps) {
  const [copied, setCopied] = useState(false);

  const generateTextReport = useCallback((): string => {
    const lines = [
      '═══════════════════════════════════════════════',
      '       TRUSTSHIELD AI — SECURITY ADVISORY REPORT',
      '═══════════════════════════════════════════════',
      '',
      `Report ID: ${reportData.id}`,
      `Generated: ${new Date().toLocaleString()}`,
      '',
      '── RISK ASSESSMENT ───────────────────────────',
      `Risk Score: ${reportData.riskScore}/100`,
      `Risk Level: ${reportData.riskLevel}`,
      `Category:   ${reportData.category}`,
      '',
      '── SUMMARY ───────────────────────────────────',
      reportData.summary,
      '',
      '── RED FLAGS DETECTED ─────────────────────────',
    ];

    reportData.redFlags.forEach((flag, i) => {
      lines.push(`  ${i + 1}. [${flag.severity}] ${flag.title}`);
      lines.push(`     ${flag.explanation}`);
      lines.push('');
    });

    lines.push('── RECOMMENDED ACTIONS ────────────────────────');
    reportData.recommendedActions.forEach((action, i) => {
      lines.push(`  ${i + 1}. [${action.priority}] ${action.action}`);
    });

    if (reportData.psychologicalTriggers && reportData.psychologicalTriggers.length > 0) {
      lines.push('');
      lines.push('── PSYCHOLOGICAL MANIPULATION TACTICS ─────────');
      reportData.psychologicalTriggers.forEach((trigger) => {
        lines.push(`  • ${trigger}`);
      });
    }

    lines.push('');
    lines.push('═══════════════════════════════════════════════');
    lines.push('This report was generated by TrustShield AI.');
    lines.push('No personal data was stored or transmitted.');
    lines.push('═══════════════════════════════════════════════');

    return lines.join('\n');
  }, [reportData]);

  const handleDownload = () => {
    const textContent = generateTextReport();
    const blob = new Blob([textContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `trustshield-report-${reportData.id.slice(0, 8)}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleCopy = async () => {
    const textContent = generateTextReport();
    await navigator.clipboard.writeText(textContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="flex items-center gap-2">
      <button onClick={handleDownload} className="btn-secondary text-sm py-2 px-4">
        <Download className="w-4 h-4" />
        Download Report
      </button>
      <button onClick={handleCopy} className="btn-ghost text-sm">
        {copied ? (
          <>
            <Check className="w-4 h-4 text-emerald-400" />
            Copied!
          </>
        ) : (
          <>
            <Copy className="w-4 h-4" />
            Copy
          </>
        )}
      </button>
    </div>
  );
}
